### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by roxfr**
Hi,
Here is the French update of the installer.
Regards,
Roxfr

### CODE REVIEW

**Review by jacobgkau — APPROVED** [review]
Thank you for the updates. There are still some strings missing from the translation, but the new and changed strings are showing up properly after selecting French in the installer.

**Comment by roxfr** [comment]
> Thank you for the updates. There are still some strings missing from the translation, but the new and changed strings are showing up properly after selecting French in the installer.

Hello,

I’m wondering if updates to the Elementary OS installer directly impact Pop Installer in Pop!_OS.
Weblate updated the Elementary OS installer and the translation 5 hours ago.
Is there a strategy for integrating these updates?

Also, I used Poedit to update with the .pot file, but I still don't see these missing strings.
Can you help me understand why this might be happening?

Thanks

**Comment by jacobgkau** [comment]
> I’m wondering if updates to the Elementary OS installer directly impact Pop Installer in Pop!_OS.

No, the Pop!_OS fork is not regularly rebased on the upstream elementary OS installer, so updates there don't automatically make it here. It's likely that Pop!_OS will replace the installer with something using Iced instead of Vala in a future version (not 24.04), and less likely that this repo would be fully rebased at this point.

> Also, I used Poedit to update with the .pot file, but I still don't see these missing strings.
> Can you help me understand why this might be happening?

We've just had a couple of other PRs to fix some problems and make some updates to the potfiles:
https://github.com/pop-os/installer/pull/295 
https://github.com/pop-os/installer/pull/298 

I see that the poedit GUI program doesn't allow updating the translation file from the source code, for some reason. I went ahead and ran `meson builddir && ninja -C builddir io.elementary.installer-pot` in another branch to update the translation template: https://github.com/pop-os/installer/pull/300 

Once that .pot translation template update has been merged, you could rebase this branch or create another one to update the French .po file with the updated strings. Thanks again for your translation work.

**Comment by jacobgkau** [comment]
@roxfr I've just rebased this branch, and it should now have an updated translation template. If you'd like, you can pull the changes, then use the `Translation` -> `Update from POT File...` option in Poedit to add the new strings to the French translation, and then they'll show up so you can translate them. Let me know if you have any trouble doing that.

**Pull request closed without merging**
