### PR TITLE
Recovery Upgrade Support

### LINKED ISSUE #178: Upgrade UI View
The pop-upgrade daemon fetches packages, then reboots the system into the recovery partition. When in the recovery partition, the installer will launch and check for `UPGRADE=1` being set. If set, it will launch an upgrade UI, chroot into the install, and upgrade the OS. On failure, the upgrade can repaired from within the recovery environment.

### PR DESCRIPTION
**Pull request by mmstick**
Closes #178
Requires https://github.com/pop-os/distinst/pull/189

### CODE REVIEW

**Comment by brs17** [comment]
Acquired screenshots thus far:

 Screenshot from 2019-04-16 01-15-48
Screenshot from 2019-04-16 01-24-11

**Comment by mmstick** [comment]
Failure likely due to a typo to `apt-get`

**Comment by mmstick** [comment]
This requires https://github.com/pop-os/distinst/pull/179 to be installed to fix the errors.

**Comment by brs17** [comment]
Below is a screenshot while the upgrade is happening.
Screenshot from 2019-04-30 16-35-26

I wonder if we should say "Upgrading" instead of "Attempting upgrade". While I understand it is an attempt, the wording above says "System is being upgraded" and I do feel like saying "attempting" sounds like there is quite the high possibility of failure (which we probably do not want to suggest).

**Comment by mmstick** [comment]
The labels are just placeholders at the moment. Any suggestions for improving the UI, features, or broken functionality?

**Comment by brs17** [comment]
Screenshot of completed upgrade:
Screenshot from 2019-05-01 20-46-27

**Comment by brs17** [comment]
I think there should be a little bit more spacing between the status update (`Attempting upgrade`) and the progress bar.
56978904-cdb2da00-6b35-11e9-9bd9-6cf687b085d0

**Comment by mmstick** [comment]
There doesn't seem to be a way to change the spacing for using the label that comes with the progress bar, but I can attach a separate label with better spacing instead.

**Comment by cassidyjames** [comment]
@mmstick if all progress bars with text appear that way, the appropriate place to fix that would be the Pop! stylesheet.

**Comment by brs17** [comment]
Having decided not to continue developing the recovery based upgrade, I am going to close this pr.

**Pull request closed without merging**
