### PR TITLE
Success view balance copy

### PR DESCRIPTION
**Pull request by isantop**
Adds a bit of copy to the success view that indicates that the device needs to restart. It doesn't indicate that the device will automatically reboot, since it won't.

### CODE REVIEW

**Comment by danrabbit** [comment]
We could do something like:

"Your device will automatically restart to %s in %i seconds."
"After restarting you can set up a new user, or you can shut down now and set up a new user later."

**Comment by cassidyjames** [comment]
@danrabbit u so smart

**Comment by cassidyjames** [comment]
@isantop see https://github.com/elementary/installer/pull/300/files

For the pop fork, we'll just want to include the second line from the two strings. Then we get free translations :tada:

**Comment by jackpot51** [comment]
Addressed in https://github.com/pop-os/installer/commit/527aab8a92ecee5f802be6b9c308a39e670edb5a

Error View:
error_view

Success View Before:
success_view_before

Success View Now:
success_view

**Pull request closed without merging**
