### PR TITLE
Remove the possibility for there to be a `none` locale

### LINKED ISSUE #192: Installer crashes when "generating locales"
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Issue/Bug Description:**
Installer suddenly crashes:

**Expected behavior:**
The OS should install fine.

**Other Notes:**
I don't have a swap patition.
Apparently, the installer fails when generating the locales:
https://hasteb.in/uyesirev.sql

I chose the following when installing the OS:
Language: English
**Region: None**
Keyboard Layout: German > Standard

### PR DESCRIPTION
**Pull request by 13r0ck**
Closes #192 by removing `None` as a country option from the installer.

### CODE REVIEW

**Review by mmstick — DISMISSED** [review]

**Comment by jacobgkau** [comment]
Is the commit message/PR title supposed to say "Remove the possibility for there to be _no_ locale"?

**Comment by mmstick** [comment]
I've wondered if it's worth it to default to a known-good well-supported locale like en_US in the failure case in distinst or the installer.

**Comment by 13r0ck** [comment]
@jacobgkau Title fixed. Sorry about that.

**Comment by 13r0ck** [comment]
If we choose to go with a fallback in distinst I'm fine having this be closed. This was just made off of discussions in QA where people have said that "There shouldn't even be a 'none' option".

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
`None` is no longer showing up in the list, and the order of the remaining countries are now unaffected. Installation still works after selecting a country.

**Pull request merged**
