### PR TITLE
fix: remove broken back button

### LINKED ISSUE #253: Back button doesn't work
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
pop-installer:
  Installed: 0.0.1~1639146907~21.10~4ba72f9
  Candidate: 0.0.1~1639146907~21.10~4ba72f9
  Version table:
 *** 0.0.1~1639146907~21.10~4ba72f9 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
The back button in the custom page doesn't work

**Steps to reproduce (if you know):**
Go into the partitionView and click back. It doesn't work.

**Expected behavior:**
Either take the user back a view, or just remove it, because there is a `Cancel Install` button right next to it. Which takes the user to the same place.

**Other Notes:**

https://user-images.githubusercontent.com/58987761/146619868-20cb742b-3855-47a5-8f77-ef549a60514d.mp4

### PR DESCRIPTION
**Pull request by 13r0ck**
Fixes #253

Screenshot from 2021-12-17 23-39-30

### CODE REVIEW

**Comment by leviport** [comment]
This looks good on 21.10, but something weird is going on with 20.04. After adding the testing branch, `pop-installer` is kept back when I try to upgrade it. If I run a `full-upgrade`, it pulls in `libgranite6` and `distinst-v2`: 


After that, the installer starts looking quite broken: 


Here's what that page should look like:

**Comment by 13r0ck** [comment]
Maybe we should test the installer on the master branch or something. I don't see how this PR could cause those breaks

**Review by jackpot51 — APPROVED** [review]

**Comment by 13r0ck** [comment]
@leviport I tried with just pulling in master on 20.04 and i get the same issue. This isn't a regression from this PR, but something that was merged previously.

**Comment by 13r0ck** [comment]
@leviport I tried pulling in just master, and I see the same regression as you without this PR. What you found isn't a regression from this PR, but something that was merged before.

Here are the terminal warnings to add to Levi's images above
Screenshot from 2022-01-05 19-33-02

**Review by leviport — APPROVED** [review]
Approving since the bug I found is not caused by this PR.

**Pull request merged**
