### PR TITLE
Fix recovery install issue

### LINKED ISSUE #119: Reinstall from recovery partition fails
**Distribution - (run ```cat /etc/os-release```)**
 Pop!_OS 18.04
 
**Issue/Bug Description**
 After doing an encrypted installation (from the imaging server), attempting to reinstall(encrypted) from the recovery partition fails.

Error logs:

```
ProgressView.vala:261: attempting to find LUKS partition automatically
ProgressView.vala:321: LVM partition not found on /dev/sda

```

### PR DESCRIPTION
**Pull request by mmstick**
@brs17 See if this fixes the issue.

Closes #119

### CODE REVIEW

**Comment by jackpot51** [comment]
To test this, boot into the recovery partition, kill the installer, add the recovery-install-fix repo, update, and relaunch the installer

**Comment by brs17** [comment]
Just got back from lunch, yes @jackpot51 already working on it!

**Comment by jackpot51** [comment]
I don't believe this will work though. It appears to change behaviour based on the user's encryption selection for the reinstall. Please try both a reinstall with encryption on top of encryption, and without encryption on top of encryption.

**Comment by brs17** [comment]
Installation failed again. Looks like kernelstub errors this time. 

img_20180502_134635

**Comment by brs17** [comment]
And yes, I was planning on doing just that, encryption over encryption and nonencrypted over encryption. I'll test the other permutations later as well.

**Comment by jackpot51** [comment]
@brs17 your EFI partition ran out of space, likely due to old kernelstub EFI files being left over from old installs

**Comment by brs17** [comment]
I thought a patch had been applied for that

**Comment by jackpot51** [comment]
No, we need to clean up old EFI files from the old install when going through recovery

**Comment by brs17** [comment]
Wiping drive and trying again.

**Comment by brs17** [comment]
Booted from a live image, used gparted to delete the partition on the drive, then rebooted and installed from the imaging server. Got the same error when trying to reinstall (unencrypted) from the recovery partition

**Comment by mmstick** [comment]
@brs17 You may need to delete excessive EFI entries with `efibootmgr`.

**Comment by jackpot51** [comment]
@mmstick the space issue is from the EFI partition itself. It would be good if distinst could remove the things added by kernelstub when it installs in recovery mode

**Comment by jackpot51** [comment]
```
/boot/efi/EFI/Pop_OS-0a590437-24b6-4bf5-aa96-377cd69bbb2b
/boot/efi/EFI/Pop_OS-0a590437-24b6-4bf5-aa96-377cd69bbb2b/vmlinuz-previous.efi
/boot/efi/EFI/Pop_OS-0a590437-24b6-4bf5-aa96-377cd69bbb2b/initrd.img-previous
/boot/efi/EFI/Pop_OS-0a590437-24b6-4bf5-aa96-377cd69bbb2b/vmlinuz.efi
/boot/efi/EFI/Pop_OS-0a590437-24b6-4bf5-aa96-377cd69bbb2b/initrd.img
/boot/efi/EFI/Pop_OS-0a590437-24b6-4bf5-aa96-377cd69bbb2b/cmdline
/boot/efi/loader
/boot/efi/loader/entries
/boot/efi/loader/entries/Pop_OS-current.conf
/boot/efi/loader/entries/Pop_OS-oldkern.conf
/boot/efi/loader/loader.conf
```

**Comment by mmstick** [comment]
Working on removal of old entries for kernelstub in distinst.

**Comment by jackpot51** [comment]
Thanks!

**Comment by brs17** [comment]
Looks like for some reason upon tribble install, two folders are created: /boot/efi/EFI/Pop_OS-UUID /boot/efi/EFI/Pop_OS-UUID2 Where one of them doesn't exist and is just taking up space.

**Comment by jackpot51** [comment]
Tribble likely needs to do the same thing

**Comment by brs17** [comment]
Now looks like I can install numerous times (done so 6 times or so) and a second entry never exists in `/boot/efi/EFI`

**Comment by jackpot51** [comment]
@brs17 does that happen without this change?

**Comment by brs17** [comment]
That's a good point, does not look like this is necessary

**Pull request closed without merging**
