### PR TITLE
Installer images

### PR DESCRIPTION
**Pull request by jackpot51**
Adds installer images and adjusts terminal style

### CODE REVIEW

**Comment by cassidyjames** [comment]
The terminal stuff was taken care of in https://github.com/pop-os/gtk-theme/pull/139, so should probably be removed from this PR.

**Comment by jackpot51** [comment]
I removed it @cassidyjames

**Comment by cassidyjames** [comment]
I noticed the language image is resizing and moving when the language below changes. It's not a major deal, but it's a little weird.

**Comment by cassidyjames** [comment]
There's also a lot of space between each image and the label. It looks like that's padding in the actual images themselves; I wonder if we could trim that out so the label is a little more attached to the image?

screenshot from 2018-04-04 11-17-14

**Comment by isantop** [comment]
As for padding in the images, we can remove it, but it might require Kate doing that as the animation images are just clear overlays, and unless the padding is 100% identical on all sides, it would need to be re-rendered in illustrator to be sure it's aligned correctly.

**Pull request merged**
