### PR TITLE
feat(i18n): Update Chinese Simplified translation

### PR DESCRIPTION
**Pull request by RX-CaO**
Update Chinese Simplified translation。

### CODE REVIEW

**Comment by n3m0-22** [comment]
@RX-CaO I'm not seeing the updated translations you have added when running the installer. Is it working on your end, or did you just add the updated translations text to the `zh_CN.po` file?

**Comment by RX-CaO** [comment]
This is the final version so far.

**Comment by n3m0-22** [comment]
There seems to be a problem `msgstr` of this line of the `zh.po` file:
```
msgid "Your device will automatically restart to %s in %i seconds."
msgstr "您的设备将会在 %i 后自动重启以进入 %s 。"
```
If I remove the translation from that line the Chinese translations work fine. I tried the same thing with the Chinese Simplified `zh_CH.po` translations, but they are still not showing up. I'll look into this further.

**Comment by RX-CaO** [comment]
I just went to check the relevant information, and this way of writing is indeed wrong. The main reason why I translated it this way is because this kind of sentence style is very strange in Chinese. I have updated a new version of the translation.

Outside of that, I had some problems when I tried to apply my translation to the software, and I don't think it was my translation that caused it.
I don't know anything about the structure of this project and I don't have ability and energy to study it. That's all I can do to provide a translation file without errors.
I am sorry to trouble you.

**Comment by n3m0-22** [comment]
Don't worry, it's no trouble. We are still looking into this since we would love to have it merged. Thank you for all you're help in trying to get this working.

**Review by n3m0-22 — APPROVED** [review]
@RX-CaO The translations are showing up now. The problem seems to be with punctuation. For instance if the English text ends with a period the Chinese Simplified must end with  。 

Example:
```
msgid "This will cancel installation and turn off this device."
msgstr "这将取消安装并关闭此计算机。"
```

Other types punctuation (e.g., ?, !, ... , :) seems to need a type of space before them. This is not a normal space. Adding it with a standard text editor would not work for me. I was able to do this with an app called Poedit. You can add a normal space using the spacebar in Poedit to each of the lines the app marks with an error. When the file is saved it becomes the proper spacing needed for the Chinese Simplified text to display.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
