### PR TITLE
DecryptMenu Enhancements

### LINKED ISSUE #128: Disk decryption focus is wrong on second visit
**Issue/Bug Description:**
When initially selecting the decryption pop-over, the focus is on the password field (which is expected/good). Moving away from this pop-over and then revisiting it, the focus is on the sentence of text and not the password (bad, see below).

broken

### PR DESCRIPTION
**Pull request by mmstick**
screenshot from 2018-05-21 13-29-45

Fixes #128 
Implements https://github.com/elementary/installer/issues/331

### CODE REVIEW

**Comment by jackpot51** [comment]
Code looks good to me.

**Comment by cassidyjames** [comment]
This should match the dialog style of the first screen. So an icon (`dialog-error`), left-aligned title text, and a non-expanded button. Also, "Ok" is not really okay as far as UI goes; what are they doing when they hit it? Are they giving up? Can they go back and try again?

I'd say a "Try Again" button that takes them back to the decryption screen would make sense at the very least, because they can always close the popover by clicking outside of it.

**Comment by mmstick** [comment]
@cassidyjames That's what it does, so I'll relabel it. Thanks for the input!

**Comment by mmstick** [comment]
@cassidyjames How's this?

screenshot from 2018-05-21 15-04-51

**Comment by cassidyjames** [comment]
@mmstick something looks a little off there. I'll pull and take a look at the code.

**Comment by cassidyjames** [comment]
The wrapping is still a little weird, but I think that's just due to the copy itself. I added an animation to the stack, corrected the stack to switch back to the correct view, and echoed a lot of the styling from the decrypt_view dialog style.

image

@mmstick do those changes make sense?

**Comment by mmstick** [comment]
@cassidyjames They do make sense.

**Comment by brs17** [comment]
When clicking away from the error message and then selecting the partition again, the error message is still displayed. I believe @cassidyjames was thinking when the focus is moved away, the error should be dismissed.

I also wonder if the password field should be cleared after dismissing the error.

**Comment by mmstick** [comment]
> When clicking away from the error message and then selecting the partition again, the error message is still displayed. I believe @cassidyjames was thinking when the focus is moved away, the error should be dismissed.

I'll look into this now.

**Comment by mmstick** [comment]
@brs17 This is ready for review / testing again.

**Comment by brs17** [comment]
Latest screenshot: 
newimage

Now the error message dismisses when selecting away from the popup menu. That probably looks good enough, right @cassidyjames ?

ISSUE: When the correct decryption key is provided, the pop-up message should go away but as seen in the screenshot below, does not.
decryptnodismiss

Related, when selecting the partition that was recently decrypted, I get the same pop-up as if the drive was still encrypted (looks identical to previous screen shot). @cassidyjames How do you think this should be handled?

ISSUE: At the custom partitioning view, if I go back to the "try or install" page and then back to the custom partitioning view as expected the disks are locked again (I assume this is a feature). If I attempt to decrypt though I get the error: `Device name already exists`. If the name that was already used can't be cleared, then my though it is that the name should append a number at the end (if data exists data1...)

**Comment by mmstick** [comment]
@brs17 Sounds like the package you got may not have contained the fixes in here. It automatically closes the popover after a successful decryption and sets an icon clarifying that it has been closed. At which point, the popover can never be opened again.

screenshot from 2018-06-14 15-38-21

**Comment by brs17** [comment]
Was able to get back to look at this again today. I've got the latest commit pulled in `5757b53` but I still do not have that lock icon.

**Comment by mmstick** [comment]
Strange. I may need to re-do this PR.

**Comment by mmstick** [comment]
I think I found the issue. Fix coming soon.

**Comment by mmstick** [comment]
@brs17 This should be working now.

**Comment by brs17** [comment]
Update: A weird issue is happening where after supposedly successful installation, an initramfs prompt appears. @mmstick is investigating.

**Comment by brs17** [comment]
Well..the weird issue went away. Must have gotten into a strange state (regardless this was not a regression with this patch). Looks good to me.

**Comment by brs17** [comment]
- [ ] Fixes #128 
- [ ] Errors appear when decrypted incorrectly
- [ ] Error message is dismissed when moving away from popup message
- [ ] Pop up message does not appear when partition is decrypted

**Comment by brs17** [comment]
Let's run it by @cassidyjames before merging

**Pull request merged**
