### PR TITLE
feat: Integrate w/ Distinst V2 DBus for Redesigned Refresh OS UX

### LINKED ISSUE #233: Updated designs for Refresh Install process initiated from the Recovery Partition.
The changes in the designs intended to streamline the Refresh OS process. The changes would also help better align the process with Refresh OS initiated from the Settings panel visually.

The chart below might help to figure out what we can show in the UI depending on things like bootloader entry, weather the Refresh OS is actually possible after decryption, and how many partitions are present. 
FlowChart

To summarize, there are four scenarios:
1. There is a bootloader entry and Refresh OS is possible.
2. There is a bootloader entry but there is no Pop!_OS installed. There are multiple partitions.
3. There is a bootloader entry but there is no Pop!_OS installed. There is only one partition - main difference is that there is no “Select another partition” button in this view (see mockups for more context):
Installer-user-account-name (2)
4. There is no bootloader entry.

The mockups could be clicked through here (use side panel on the left to switch between the four outlines scenarios: https://www.figma.com/proto/xdEDKxKMRHrdN0tMqsQm0h/Refresh-Install?node-id=16%3A538&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=16%3A538&show-proto-sidebar=1
In addition, this is another way to look at the mockups: https://www.figma.com/file/xdEDKxKMRHrdN0tMqsQm0h/Refresh-Install?node-id=0%3A1

### LINKED ISSUE #235: Change the default user account Avatar
Artwork incoming

### PR DESCRIPTION
**Pull request by mmstick**
Completely changes the Refresh OS UX in the installer, using the new Distinst V2 DBus API.

Requires the DistinstV2 DBus service to be installed and active.
Requires https://github.com/pop-os/default-settings/pull/120

Closes #233 
Closes #235

### CODE REVIEW

**Comment by mmstick** [comment]
distinst-v2 is buildable now, so it should be possible to test it today.

**Comment by jacobgkau** [comment]
Should `pop-installer` depend on `distinst-v2` since it's required for installation to work? It doesn't look like it's trying to pull it in right now.

**Comment by jacobgkau** [comment]
On the password page, I can't go back to change my username:
Screenshot from 2021-11-02 16-18-10
I don't think this was intended with https://github.com/pop-os/installer/issues/239. The username page shouldn't have a back button to go to the disks page, but the password page should still have a back button to go to the username page. (At least, that's how I read it-- I could be wrong? @maria-komarova)

**Comment by maria-komarova** [comment]
That's right, that was the intention @jacobgkau

**Comment by 13r0ck** [comment]
On a refresh install should there be a UI warning that the decryption password is wrong? @maria-komarova 

https://user-images.githubusercontent.com/58987761/139910024-0498fff9-e263-4508-ab7e-3370943fb19e.mp4

**Comment by maria-komarova** [comment]
Yes, good catch @13r0ck, there should be a similar messaging as on the decrypt screen when someone is turning on the computer.

**Comment by 13r0ck** [comment]
1. After clicking `Decrypt` animation is in the wrong direction
animate_wrong_way
2. Clicking `Cancel Install` shows a non-previous view
different_screen
3. After the result in # 2, The refresh is not restarted, it is resumed
doesn't_reset_install
4. On a clean install this back button should be removed (according to #239)
back_should_be_removed

**Comment by jacobgkau** [comment]
Is this supposed to be pulling in `distinst-v2` as a dependency? Also, might be a good idea to rebase.

**Comment by jacobgkau** [comment]
On d4d403b, I'm not seeing a Refresh option appear when the installation is encrypted and I start the installer from a live disk or the Recovery partition. (It does show up when the installation is not encrypted.)

**Comment by mmstick** [comment]
Did the distinst-v2 service start?

**Comment by jacobgkau** [comment]
> Did the distinst-v2 service start?

Ah, no, I had to start `com.system76.Distinst.service` manually. It's showing up now, and seems to work now.

**Comment by mmstick** [comment]
Will fix the service

**Comment by mmstick** [comment]
New version of distinst-v2 has been built in master

**Comment by jacobgkau** [comment]
The service is now called `distinst-v2`, it started automatically, and I now got the `Refresh Install` option without having to manually start it, as expected.

**Comment by jacobgkau** [comment]
The `Cancel Installation` button does not work after decrypting a drive:

Screenshot from 2021-11-30 20-16-04

Every time I click it, the terminal says:

```
(io.elementary.installer:5064): Gtk-WARNING **: 20:15:23.972: Given child of type 'RefreshView' not found in GtkStack
```

**Comment by jacobgkau** [comment]
Cancelling works now. If I cancel, then try to refresh again and proceed this time, I'm asked for the decryption password again and decryption fails with `Device name already exists`.

**Comment by jacobgkau** [comment]
The mockup does show a `Back` button on this page, which isn't present in the screenshot above.

**Comment by jacobgkau** [comment]
The mockup shows a `Back` button on the encrypted partition selection page, but there is not one:
Screenshot from 2021-12-01 15-50-29

Also, if I unlock, go back/cancel the refresh, then attempt to refresh again, I still fail to unlock a second time:
Screenshot from 2021-12-01 15-51-33

It looks like 17c176ba91cd4103479b9ad246d4e8b54e4ebfee added the UUID to the end of the devname, but wouldn't the UUID be the same each time anyway?

**Comment by jacobgkau** [comment]
If I select an encrypted device, then cancel (before or after entering a decryption passphrase), then decrypt again and enter the passphrase, I get multiple decrypted device entries:

Screenshot from 2021-12-02 17-56-44

Instead of the random string, would there be a problem with just not asking for the decryption passphrase if the device is already decrypted? Seems like either that, or cleaning up/removing the decrypted devices when cancelling, will still be needed.

**Comment by jacobgkau** [comment]
The mockup also has the `Decrypt` button green (suggested) on the page where the decryption password is entered, but it's not green in 018d852.

**Comment by mmstick** [comment]
It should already be remembering what encrypted devices have been decrypting. There's an issue if it's not.

**Comment by jacobgkau** [comment]
On 26651f0, the back button on the `Select Encrypted Partition` page does not work; I get `located encrypted devices` in the terminal every time I click it. It also seems off that I don't need to select any devices (and none are selected by default) in order for the `Select` button to become active on this page.

I am still getting multiple entries after attempting to cancel before unlocking, then proceeding to unlock.

**Comment by mmstick** [comment]
Installing another VM so I can figure this out.

**Comment by jacobgkau** [comment]
On afcae45, if I decrypt successfully, cancel back to the `Select Encrypted Partition` page, then enter the decryption password again, I'm just taken back to the `Select Encrypted Partition` page, instead of the list of decrypted volumes. I get this in the terminal when this happens: [out.txt](https://github.com/pop-os/installer/files/7645346/out.txt)

I still don't have the encrypted device visually selected when entering the `Select Encrypted Partition` page.

**Comment by mmstick** [comment]
Canceling on that page loads the view that lets you select between Clean Install and Refresh. At least in my VM, canceling and then selecting the refresh mode again skips the encrypted partition select view since there are no encrypted partitions left to decrypt, and instead shows the OS on the previously-decrypted volume.

**Comment by jacobgkau** [comment]
This is what I'm seeing on 92e321e:

https://user-images.githubusercontent.com/7199422/144523164-f33e55e7-7b22-4297-bf16-a3be443711a2.mp4

As you can see, after cancelling one time and then attempting to proceed a second time, it's continuing to show me the `Select Encrypted Partition` screen and asking for the password in a loop.

**Comment by mmstick** [comment]
This may fix it. The disk information will be rescanned again each time the refresh OS select page is loaded. Decrypted partitions should not be shown as an options for decrypting again.

**Comment by jacobgkau** [comment]
Not seeing any behavior change from the above video on 8667434.

**Comment by mmstick** [comment]
What's the logs you're getting?

**Comment by jacobgkau** [comment]
Here's log output after decrypting, cancelling, and attempting to decrypt again/getting kicked back to the `Select Encrypted Partition` list once: [out.txt](https://github.com/pop-os/installer/files/7650718/out.txt)

**Comment by mmstick** [comment]
I have an idea.

**Comment by jacobgkau** [comment]
The logic is working now. After I unlock the first time, if I cancel and then select `Refresh Install` again, I'm brought right to the `Fresh Install` page with the single decrypted volume.

A few more points:

- If I select `Clean Install` on the `Refresh Or Install` page, then click `Back` on the `Install` page, I'm taken all the way back to `Keyboard Layout`, when I would expect to go only one page back to `Refresh or Install`.

- Also, if I unlock via the `Refresh Install` option on the `Refresh Or Install` page, then go back to the `Refresh Or Install` page and select `Clean Install` instead, then I see `Refresh Install` a second time as one of the options on the `Install` page. The mockups don't address this (in fact, the mockups seem to have forgotten that `Custom (Advanced)` was an option on the `Install` page), but I would not expect to see `Refresh Install` as an option on the `Install` page anymore since we already chose not to refresh on the `Refresh Or Install` page.

- Finally, the `Refresh Or Install` label on that page should actually say `Refresh or Install` (with a lowercase `o`) according to the mockups.

**Comment by mmstick** [comment]
It's letting you select an OS to refresh without the option to choose an encrypted partition?

**Comment by jacobgkau** [comment]
> It's letting you select an OS to refresh without the option to choose an encrypted partition?

The second time, yes, as expected.

New issue now, the `Refresh or Install` page no longer has a `Back` button to go back to language/keyboard layout selection. I could have sworn that was there before. (Also noticing that the `Try Demo Mode` button should be present on the `Refresh or Install` page; a user shouldn't have to select `Clean Install` to get that option.)

**Comment by jacobgkau** [comment]
This is working great on encrypted and decrypted systems now. The new default profile picture is also working for clean installs.

This is kind of a nitpick, but if I select Refresh Install, then select an encrypted partition, then click `Back` on the password page, I go two pages back to `Refresh or Install`. Can that back button on the password page go a single page back to `Select Encrypted Partition` instead?

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
After starting a refresh from within the OS, with `MODE=refresh` within `/cdrom/recovery.conf`, the installer on c4330a3 is launching to the language selection, not the decryption password page like it used to. It's then giving me the option to refresh or clean install, where I shouldn't be seeing the option to clean install in this mode.

**Comment by mmstick** [comment]
Yes, this PR changes the refresh mode's behavior, so it will no longer do that. This is the new expected behavior

**Comment by jacobgkau** [comment]
@maria-komarova Just to confirm, the user should have to select `Refresh Install` again (and should see the `Clean Install` option) even if they already initiated a refresh install from within the OS?

**Comment by mmstick** [comment]
@jacobgkau I think I've got this now. Still doing some testing to verify.

**Comment by jacobgkau** [comment]
On b883e4d, I'm getting a blank screen launching the installer in a live disk.

Screenshot from 2021-12-07 19-03-10

**Comment by jacobgkau** [comment]
I am no longer seeing the option to refresh when booted from a live disk.

**Comment by mmstick** [comment]
There should still be a refresh button when a boot entry is found

**Comment by mmstick** [comment]
Was able to successfully refresh from a live environment this time.

**Comment by jacobgkau** [comment]
- [X] Refresh from live environment
- [X] Refresh from manual recovery
- [X] Refresh from OS

All of the back/forward buttons in the refresh flow are working as expected. Still doing some other testing.

Regarding flow, I did notice that if I start a refresh from within the OS, once the installer starts, I have the option to cancel the refresh, which brings me back to the `Refresh or Install` page. That's fine, but it won't fully cancel the refresh, since the system still boots back to the Recovery partition in refresh mode until the refresh is performed. This matches the behavior from before the update (the only difference is that now, both the `Decrypt Install` and `Refresh Install` pages have back/cancel buttons, where only the `Refresh Install` page had a cancel button before.)

**Comment by jacobgkau** [comment]
Before this update, the dm-crypt volume was always called `cryptdata`. On d16d292, clean installing still gives me `cryptdata`, but refreshing causes the volume to be named `cryptdata-xxxx`, where `xxxx` is a random 4-character string.

This doesn't seem to cause any impact (for example, following the instructions in the "Use the Recovery Partition" support article still allows me to decrypt the volume using the name `cryptdata`, without knowing the 4-character ID), but it does change what the prompt at boot looks like.

I thought the random string was done to try and prevent duplicate decrypted entries from showing up in the list, but it didn't fix that problem at the time (unless it was still used in the later fix.) Is the id still serving any purpose? If so, can this be done in a way that doesn't change the volume's name?

**Comment by mmstick** [comment]
I think it can be changed back to `cryptdata` now. But in general the name doesn't matter.

**Comment by mmstick** [comment]
Actually, seems I can't because then there'd be a conflict if two encrypted partitions were decrypted.

**Comment by mmstick** [comment]
Added a check for `/dev/mapper/cryptdata`. If it exists it'll create the `-$d` variant.

**Comment by jacobgkau** [comment]
- [X] Clean install from live environment
- [X] Refresh from manual recovery
- [X] Refresh from OS
- [X] Clean install from manual recovery
- [X] Custom install from live environment
- [ ] Refresh from live environment

The decryption screen no longer has extra characters appended after refreshing.

After performing a custom install (512MB FAT32 /boot, and one XFS /), the installer in a live disk offers to refresh on the first page, but the `Refresh Install` page is empty, so I cannot proceed:

Screenshot from 2021-12-08 16-29-31

Some potential ways this should be handled instead:
- The `Refresh Install` page should list the installation (this would be best.)
- The first page should not offer to refresh if it's not possible (I understand it's just looking at the bootloader entry, though.)
- If a bootloader entry is present but refreshing is not possible, instead of seeing this blank `Refresh Install` page, I should see something similar to the "Installer-Install-NoPop!_OS" page in the mockups.

**Comment by jacobgkau** [comment]
The issue above does not happen with a standard decrypted install, so it's limited to custom installs, just to clarify.

**Comment by jacobgkau** [comment]
I'm still seeing the blank page on a9b2576:

Screenshot from 2021-12-08 17-45-09

**Comment by mmstick** [comment]
Doing the custom install to find out why

**Comment by mmstick** [comment]
Seems to be working now

**Comment by jacobgkau** [comment]
- [X] Clean install from live environment
- [X] Refresh from manual recovery
- [X] Refresh from OS
- [X] Clean install from manual recovery
- [X] Custom install from live environment
- [X] Attempting to refresh a custom install from the live environment suggests a clean install

b695d8d is looking good so far, I'm adding a second drive to the system to do a few final tests.

**Comment by jacobgkau** [comment]
In a system with two disks:
- [X] Clean install installs to the correct disk
- [X] Refresh install initiated from within the OS installs to the correct Pop!_OS installation
- [ ] Refresh install initiated from Recovery allows selecting between both encrypted disks, then installs to the correct one

I noticed that when booted from a USB live disk, with two internal SSDs installed, one encrypted and one custom, if I select `Refresh Install` from the `Install` page, then click `Back`, I'm taken to the `Refresh or Install` page, not the `Install` page like I would expect. However, that's really not critical, since either selecting `Clean Install` or clicking `Back` and selecting a language again both bring me back to the `Install` page.

Something else I noticed was that if I have two encrypted drives and select `Refresh Install`, I do see both encrypted drives listed; but if I decrypt one, and see the decrypted volume on the `Refresh Install` page, then click `Cancel Installation`, next time I select `Refresh Install`, I only see the remaining drive that has not been decrypted. Once I decrypt that one, I only see the decrypted volume from the second drive. So there's no way for me to refresh the OS on the first drive once I cancel out of it the first time.

**Comment by mmstick** [comment]
Were those two encrypted partitions separate encrypted installs?

**Comment by jacobgkau** [comment]
> Were those two encrypted partitions separate encrypted installs?

Yes. Did a clean encrypted install to one drive, then a clean encrypted install to the other drive.

**Comment by jacobgkau** [comment]
I'm pretty sure for the multi-disk case to work, we'd need to show all encrypted drives in the list, whether they're already decrypted or not. The only page that should be skipped if it's already decrypted would be the password page.

**Comment by mmstick** [comment]
Then I'll deactivate them on returning to one of the options views.

**Comment by jacobgkau** [comment]
I'm seeing 1ef2c2a go back to the `Select Encrypted Partition` page after entering a decryption password (without the newly-decrypted drive listed), I'm assuming that's why this was marked as draft.

**Comment by mmstick** [comment]
Yeah, I got it working now.

**Comment by jacobgkau** [comment]
I'm still seeing the same issue on b73aafc. After I enter the decryption password, I'm brought back to the `Select Encrypted Partition` page with the newly-decrypted partition removed from the list.

**Comment by mmstick** [comment]
I'm not seeing the behavior, but this last commit undoes some of the code that was removed which I think may be causing it.

**Comment by jacobgkau** [comment]
I'm seeing some strange selection behavior in the `Select Encrypted Partition` page now (on 006d159):
Peek 2021-12-09 03-21

Additionally, while I am no longer being sent back to the `Select Encrypted Partition` page after entering the password, I am now being asked for the password in a loop (staying on the same page):
Peek 2021-12-09 03-23

Here is the terminal output from this session, in case it's useful: [out.txt](https://github.com/pop-os/installer/files/7681972/out.txt)

**Comment by mmstick** [comment]
Undid the other portion if this is happening in the refresh mode. Also added logging in a lot of places so the logs will be more useful.

**Comment by jacobgkau** [comment]
On d468b48, I am able to decrypt a partition now.

In the encrypted partition list, the `Select` button greys out once I change the selection.

Peek 2021-12-09 16-05

**Comment by jacobgkau** [comment]
In a system with two encrypted disks:
- [X] Clean install installs to the correct disk
- [X] Refresh install initiated from within the OS installs to the correct Pop!_OS installation
- [X] Refresh install initiated from Recovery allows selecting between both encrypted disks, then installs to the correct one

There is another design issue. If a system has two installations, one encrypted and one non-encrypted, selecting `Refresh Install` from a live disk brings me to the `Refresh Install` page with only the non-encrypted installation listed. I have no way to refresh the encrypted installation in this scenario. (If it instead brought me to the `Select Encrypted Partition` page as the mockups show, then I would only see the encrypted partition and would have no way to refresh the non-encrypted installation.)

One other thing I've noticed is that refresh installs wipe out the user's profile photo, and reset it back to GNOME's stock default, as opposed to our branded default that's set by the installer during initial installation. Options here would be to ask the user to select a profile photo again during refresh (which seems excessive), have the installer set it to our branded default at refresh, or leave it as-is with the GNOME default after refresh.

We may need input from @maria-komarova or others on how to proceed with these.

**Comment by mmstick** [comment]
It may not be a big deal since it's not common to have both an encrypted and unencrypted install. But I think the best path to supporting this strange setup is to show operating systems alongside encrypted volumes.

**Comment by jacobgkau** [comment]
> It may not be a big deal since it's not common to have both an encrypted and unencrypted install. But I think the best path to supporting this strange setup is to show operating systems alongside encrypted volumes.

I agree, showing encrypted partitions and decrypted OS's on the same page, and simply replacing an encrypted partition with the decrypted OS once it's decrypted, is the simplest way to support this that I can think of. This would be a change from the mockup, though.

**Comment by mmstick** [comment]
Fixing the user icons would require patching distinst to add `/var/lib/AccountsService/` to the list of directories that are backed up and restored.

**Comment by jacobgkau** [comment]
> Fixing the user icons would require patching distinst to add `/var/lib/AccountsService/` to the list of directories that are backed up and restored.

Do you think it's conceivable that a problem might exist in that directory that a user would try a refresh to fix?

**Comment by mmstick** [comment]
I don't think so. The only contents are icons used by users and details about a user's default session, language locale, icon, and whether the account should be visible on the login screen.

**Comment by jacobgkau** [comment]
As long as "default session" doesn't mean I'll have a problem if I set my default to another DE and then try to refresh back to COSMIC, that sounds reasonable.

**Comment by jacobgkau** [comment]
Ok. On the other issue, 405fb2c is not enough to fix the problem, I'm still going to the `Refresh Install` (non-encrypted only) page instead of the `Select Encrypted Partition` page. (And we'll probably want to rename the `Select Encrypted Partition` page if it's also showing unencrypted partitions... but we might want to wait for additional direction on this.)

**Comment by jacobgkau** [comment]
If we go the route of combining those two pages, we'll also have to consider what will happen if a user decrypts a volume and it doesn't contain an OS that can be refreshed.

**Comment by jacobgkau** [comment]
I'm getting a segmentation fault and the installer is crashing when I select `Refresh Install` from a live disk on 313ae39. Here is the terminal output: [out.txt](https://github.com/pop-os/installer/files/7688134/out.txt)

**Comment by jacobgkau** [comment]
Wait, it didn't happen the second time...

**Comment by jacobgkau** [comment]
I got another segmentation fault after decrypting one partition (with a non-encrypted partition also present), cancelling, and trying to enter `Refresh Install` again, so I think something is going on with it. [out.txt](https://github.com/pop-os/installer/files/7688156/out.txt)

**Comment by jacobgkau** [comment]
Screenshots of the flow on 313ae39:
Screenshot from 2021-12-09 20-14-09
Screenshot from 2021-12-09 20-14-22
Screenshot from 2021-12-09 20-14-33

Note that in the last screenshot, the non-encrypted partition (not the newly-decrypted partition) was actually selected by default; I selected the newly-decrypted partition before taking the screenshot. I think if the user decrypts a partition, that one should be selected by default.

Another functional issue is selecting the non-encrypted option on the _first_ page and clicking `Select` does nothing.

I think the names of the pages before and after the decryption should match. I also think the button labels need to match between both pages. Aside from the issues, this flow should work for all use cases.

However, what @maria-komarova was proposing was to have the second page after a decryption only show the single newly-decrypted partition, without the non-encrypted one present.

**Comment by jacobgkau** [comment]
A problem I see with the linear case is what happens if the user decrypts the encrypted partition and it doesn't contain a refreshable OS. Do we go back to the list with that encrypted partition removed? (That would be opposite behavior of when it does contain a refreshable OS.) Or do we show a message at that point suggesting a clean install, even if other partitions could be refreshed?

The flow captured in the above screenshots does not have that problem, because we always go back to that page after decrypting.

**Comment by mmstick** [comment]
Yes it should be going back to the list with that partition removed. The volumes aren't deactivated until the back button is selected.

**Comment by mmstick** [comment]
There's also currently no way to distinguish about where a refreshable OS came from.

**Comment by jacobgkau** [comment]
> There's also currently no way to distinguish about where a refreshable OS came from.

That's true, showing only what's inside the decrypted partition would solve that problem, otherwise an additional label to show the containing partition name might be warranted.

**Comment by jacobgkau** [comment]
Ok, we're proceeding with the "all encrypted & decrypted options on the same page" design; after decrypting, we go back to the full list with the encrypted partition removed and the decrypted OS added.

Some outstanding issues with 313ae39, just to clarify (this system has one encrypted and one decrypted OS):
- I seem to get a segmentation fault the _first_ time I select `Refresh Install` in a live disk.
- Selecting a non-encrypted OS on the `Select OS or Encrypted Partition` page and clicking `Select` does nothing.
- If I select the encrypted OS and decrypt it, the label on the next page is `Refresh Install` when it should still be `Select OS or Encrypted Partition`.
- Clicking `Cancel Installation` from that second page, then selecting `Refresh Install` again on the `Install` page, leads to another segmentation fault.

**Comment by jacobgkau** [comment]
Still getting a segmentation fault on the first `Refresh Install` after boot on e1170dd. [out.txt](https://github.com/pop-os/installer/files/7688594/out.txt)

**Comment by mmstick** [comment]
In process of setting up a VM that can replicate the setup

**Comment by mmstick** [comment]
Found cause. Update soon

**Comment by jacobgkau** [comment]
On 33ae99f, attempting to refresh a non-encrypted install crashed:
Screenshot from 2021-12-09 22-58-40

Logs: [out.txt](https://github.com/pop-os/installer/files/7688969/out.txt)

**Comment by jacobgkau** [comment]
After the above crash, I no longer see that non-encrypted installation as an option, even after powering off and back on to reset the testing. That partition now boots to initramfs/busybox.

**Comment by jacobgkau** [comment]
The above crash and subsequent boot failure does not happen when refreshing an encrypted installation; it's exclusive to refreshing non-encrypted installations. This is still on 33ae99f.

**Comment by jacobgkau** [comment]
On 3c373b3, refreshing the non-encrypted installation works now.

I'm still seeing the wrong decrypted installation selected right after I decrypt an encrypted partition:
Peek 2021-12-10 00-20

Can we make sure that after a partition is decrypted, the newly-decrypted installation is the one that's selected? (If there's no reliable way for distinst-v2 to map these together right now, then at least assuming it's the first "dm-" device would be better than nothing.)

**Comment by mmstick** [comment]
I should be able to sort them

**Comment by jacobgkau** [comment]
Ok. I also don't like that the order is switching, but I understand it's alphabetical right now. If the sorting takes care of that too, it would be great. Otherwise, having encrypted devices listed after decrypted OS's would at least mitigate this use case, which would be good enough. (The actual ordering isn't a show-stopper, though, as long as the right one's selected after decrypting.)

**Comment by jacobgkau** [comment]
The name of the page is still changing from `Select OS or Encrypted Partition` to `Refresh Install`. Because these are supposed to be the same page, it does not make sense for the name to be different.

Because selecting a non-encrypted OS on the first page immediately begins the refresh, calling the combined page `Select OS or Encrypted Partition to Refresh` or something similar might make it more clear what's about to happen. There's currently no mention of the word "refresh" on that page for non-encrypted installs.

**Comment by jacobgkau** [comment]
149d63a is working nicely to select the decrypted partition.

**Comment by jacobgkau** [comment]
I suppose the current flow will keep things more or less in line with the mockup for encrypted partitions, at the cost of a lesser experience (lack of information) for non-encrypted users, if we keep the page names as they are right now.

**Comment by jacobgkau** [comment]
@mmstick Can you make the green `Select` button on the first `Select OS or Encrypted Partition` page turn into a red `Refresh Install` button when a non-encrypted OS is selected? If we do that, and change the label on the second page to match the first ("Select OS or Encrypted Partition"), then I think we'll be okay from a UX standpoint. (It would also be good to have the back buttons' labels match, just for consistency.)

Sorry for several comments in a row, was talking it through with Levi.

**Comment by jacobgkau** [comment]
On 14b5022, the window is getting wider when I enter the Refresh Install page.
Peek 2021-12-10 00-48
This is still happening on 22b1c70.

**Comment by jacobgkau** [comment]
It's looking great. Will now do the functionality testing to make sure it's still working.

**Comment by jacobgkau** [comment]
Two disks, one encrypted/one non-encrypted:
- [X] Live disk can select between encrypted & decrypted disk, and installs to the correct disk (tested with encrypted)
- [X] Manual recovery can select between encrypted & decrypted disk, and installs to the correct disk (tested with decrypted)
- [X] Refresh install initiated from encrypted OS installs to the correct location
- [X] Refresh install initiated from decrypted OS installs to the correct location

Two disks, both encrypted:
- [X] Clean install installs to the correct disk & defaults to correct profile icon
- [X] Refresh install initiated from within the OS installs to the correct Pop!_OS installation
- [X] Refresh install initiated from Recovery allows selecting between both encrypted disks, then installs to the correct one

-----

In a system with two installations, one encrypted and the other non-encrypted, when I initiate a refresh from the encrypted disk, after entering my decryption password, I see both installations listed as option for the refresh, but the correct one is preselected:

Screenshot from 2021-12-10 01-25-25

When I initiate a refresh from the non-encrypted disk, I only see the non-encrypted disk available:

Screenshot from 2021-12-10 01-35-43

This is inconsistent (the second behavior is more desirable), but I'm ignoring that for now since it is not critical.

-----

In a system with two encrypted installs, after I decrypt one, I have the other auto-selected, instead of the newly-decrypted device:

Peek 2021-12-10 01-57

This is an edge use case, and the user should recognize that the decrypted OS is the new option after unlocking one of the drives, so I think this can also be fixed after release.

---

I am also only able to unlock one drive at a time:

Peek 2021-12-10 01-58

Given that the decrypted OS always has the same name, and the remaining encrypted drive in the list is the one that's _not_ about to be refreshed, this is confusing and not ideal. The conversation earlier sounded like both of these should be able to be decrypted at the same time. However, it sounded like distinst-v2 changes would be required in order for both decrypted OS's to be identified by their physical devices or encrypted partitions. This can also probably be deferred.

(On the positive side, this one will always require user intervention to get past, since just pressing "Enter" over and over will just decrypt the drives again and again. The user will need to click the decrypted OS to proceed, so they will hopefully understand what's going on when they do that.)

---

I do not anticipate any further issues since the two-disk tests have all passed, but I will finish the one-disk testing later tonight. Please do not make any further commits to this branch in the meantime.

**Review by jacobgkau — APPROVED** [review]
Single-disk testing has passed:
- [X] Clean, encrypted install from live environment (includes new profile icon)
- [X] Refresh from manual recovery (follows the mockup flow closest)
- [X] Refresh initiated from OS
- [X] Clean, non-encrypted install from manual recovery (includes new profile icon)
- [X] Refresh initiated from OS
- [X] Custom install from live environment
- [X] Attempting to refresh a custom install from the live environment suggests a clean install

`libgranite6` still needs to be released from proposed on Impish before or alongside this `pop-installer` update. (The necessary `pop-default-settings` update has already been released.)

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
