### PR TITLE
Keyboard Layout Selection Improvement

### LINKED ISSUE #116: Spanish language does have link to Spanish keyboard
**Distribution - (run ```cat /etc/os-release```)**
Pop!_OS  18.04 iso #17 
 
**Issue/Bug Description**
After selecting Spanish language, I would expect a second screen selecting the specific kind of Spanish. Regardless if this is available or not, the next page where keyboard selection is chosen, should default to a Spanish keyboard. This is the case for the other primary languages (English, Chinese, French, Portuguese, Russian, German).

**Expected behavior**
After selecting Spanish, a Spanish keyboard is the default suggestion.

### PR DESCRIPTION
**Pull request by mmstick**
If you select Spanish, you will get a Spanish keyboard layout now.
Likewise, if you select Polish, you will get a Polish keyboard layout.

Closes #116

### CODE REVIEW

**Comment by brs17** [comment]
@mmstick So it looks like initially selecting Spanish, will suggest a Spanish keyboard. :+1: 

However, I decided to go back and select a different language. That worked as well. Then when I selected Spanish again, it suggested the previous language's keyboard (not Spanish)

**Comment by brs17** [comment]
And now, it looks like the installer is using 100% CPU and the fans are spinning full. The machine is just sitting on the keyboard page of the installer

**Comment by mmstick** [comment]
It's probably because the existing usage of `Idle.add` executes repeatedly, as fast as possible. Using `Timeout.add` should prevent it from getting out of hand. I've also noticed the other issue, and I've been looking for the fix. It can cause some invalid configurations to happen, such as choosing a language with a default country, then going back and choosing a language that's not mapped to a country.

**Comment by mmstick** [comment]
Or not, I'm having some issues setting text in text fields.

**Comment by brs17** [comment]
Looks good! @mmstick

**Pull request merged**
