### PR TITLE
standardize keyboard behavior

### LINKED ISSUE #249: Return Clears Selection
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
pop-installer:
  Installed: 0.0.1~1639146907~21.10~4ba72f9
  Candidate: 0.0.1~1639146907~21.10~4ba72f9
  Version table:
 *** 0.0.1~1639146907~21.10~4ba72f9 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Enter clears the selected option.

**Steps to reproduce (if you know):**
Click option, press enter.

**Expected behavior:**
Enter should select option and then select the next_button, like it does if the option is focused

**Other Notes:**

enter clears

### PR DESCRIPTION
**Pull request by 13r0ck**
Like #251, but for the install type selection pages
Closes #249

Screenshot from 2021-12-17 23-34-38

### CODE REVIEW

**Comment by jacobgkau** [comment]
Rebased on master.

**Comment by jacobgkau** [comment]
Fixes https://github.com/pop-os/installer/issues/249. Navigating the installation type page solely with the keyboard now requires pressing Spacebar to select an option followed by Enter to proceed, the same as on the Disks page.

It does look like the decryption page needs a similar fix: decrypt If this PR is trying to standardize, can we address that at the same time?

**Comment by 13r0ck** [comment]
Ya I can do that in this PR too

**Review by mmstick — DISMISSED** [review]

**Comment by 13r0ck** [comment]
@jacobgkau last commit didn't work, it should work now. Sorry about that

**Comment by jacobgkau** [comment]
This is working perfectly in a USB live disk.

In Recovery mode, on the "Refresh or Install" page, the `Back` button is focused by default instead of the first item in the list (which would be `Refresh Install`). This means pressing Enter repeatedly will end up going between two pages:

Peek 2022-02-01 23-54

Can we get the list focused (not selected, just focused) on this page by default so pressing Enter does nothing until the Spacebar is pressed to select something? That would match the live disk's behavior.

**Comment by 13r0ck** [comment]
Yep I'll start on that

**Comment by 13r0ck** [comment]
I fixed focus there, and on a clean install, the first disk is now focused rather than "cancel install"

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
