### PR TITLE
Update tr.po

### PR DESCRIPTION
**Pull request by TeknoMobil**
Hello translation is complete.

### CODE REVIEW

**Comment by cassidyjames** [comment]
@brs17 is System76 maintaining translations manually in this repo now? If not, the translations should be submitted to the upstream https://l10n.elementary.io/projects/installer/ to be synced down here later. Otherwise these will just get overwritten during the next sync.

**Comment by mmstick** [comment]
@cassidyjames We're already greatly out of sync, so translations would differ either way.

**Comment by brs17** [comment]
@cassidyjames you're right, I had asked an engineer if things had differed enough where they wouldn't be of value upstream, without doing the due diligence to check myself. Thank you for keeping eyes out on this!

@TeknoMobil please go ahead and add these translations to upstream at the link Cassidy provided.

**Comment by brs17** [comment]
@cassidyjames you're right, I had asked an engineer if things had differed enough where they wouldn't be of value upstream, without doing the due diligence to check myself. Thank you for keeping eyes out on this!

@TeknoMobil please go ahead and add these translations to upstream at the link Cassidy provided.

**Comment by brs17** [comment]
@mmstick I believe things vary less than they we first thought.

**Comment by WatchMkr** [comment]
Hey @cassidyjames, as we had discussed when you guys were here, we've been maintaining and shipping this for so long we have taken on the upstream responsibilities for the project. We're doing our best not to do things that break the original design concepts or our shared use of the project. But let us know if there's something we've missed.

With all that, I think it makes sense that the syncs come from our repo down to yours. Let us know if there's anything we can do to make that easier. I recall a release tag or something that you guys suggested.

**Comment by TeknoMobil** [comment]
Hi
https://l10n.elementary.io/ This site won't open
If there is a special address for localization, I can do the translation from there.

**Comment by brs17** [comment]
> Hi
> https://l10n.elementary.io/ This site won't open
> If there is a special address for localization, I can do the translation from there.

@TeknoMobil , no I was getting confused between projects. This is a sufficient place to provide translations for the current time. We will get this pr merged soon!

**Pull request closed without merging**
