### PR TITLE
Encrypt using same password by default

### LINKED ISSUE #232: Make checkbox selected by default on the Drive Encryption screen.
The checkbox for "Encryption password is the same as user account password." might be better checked by default to save people a click.
Installer-encryption

### PR DESCRIPTION
**Pull request by 13r0ck**
Closes #232 
Fixes #236

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
This works to get the check box checked by default 🎉. However, the check box is still focused, rather than the Encrypt button (so pressing Enter or Spacebar toggles the checkbox by default, instead of continuing.)

Screenshot from 2021-11-04 20-08-33

The mockups in https://github.com/pop-os/installer/issues/232 do not include a focus indicator. Is the checkbox being focused correct so we force more consideration on this page, or should the Encrypt button be focused to make proceeding with the recommended action easier?

**Comment by 13r0ck** [comment]
I agree. I would prefer if the focus was on the encrypt. @maria-komarova should I change the focus with this PR too?

**Comment by maria-komarova** [comment]
Yes, good point, focus on the Encrypt sounds good to me.

**Comment by 13r0ck** [comment]
👍👍 I'll get that fixed in a bit

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Looks good now:
Screenshot from 2021-11-05 15-19-11
Tested with 21.10 Intel and 20.04 NVIDIA.

**Pull request merged**
