### PR TITLE
Set mount after closing menu, & disallow BIOS systems to set /boot/efi

### PR DESCRIPTION
**Pull request by mmstick**
This will:

- Prevent the user from setting `/boot/efi` as a mount when in a BIOS environment.
- Fix custom mount fields from overriding set mounts by only setting mounts after closing the menu

### CODE REVIEW

**Comment by brs17** [comment]
- [ ] Prevent the user from setting /boot/efi as a mount when in a BIOS environment.
- [ ] Fix custom mount fields from overriding set mounts by only setting mounts after closing the menu

**Comment by brs17** [comment]
When trying to use 2 partitions as "Custom", the second Custom will wipe the `Use partition` flag from the first one.

I am also thinking we should interpret a Custom mount of `/` as Root. (Not allow two root partitions)

**Comment by mmstick** [comment]
@brs17 I think those issues are fixed now.

**Comment by brs17** [comment]
A "custom" mounting point of `/` should (after that popup message is dismissed) change to the `root` mounting point.

**Comment by mmstick** [comment]
Now working on this.

**Comment by brs17** [comment]
Looking better, now once the root partition has changed, the option for mount point should be a blank custom option

**Pull request merged**
