### PR TITLE
Remove Disk Bar CSS

### LINKED ISSUE #29: StorageBar widget structure
There are still a few things screwy with the widget structure, making its themability in stylesheets broken.

For example, this is a Granite.StorageBar in the elementary stylesheet:

screenshot from 2018-04-04 09-09-44

This is master as of right now, also in the elementary stylesheet (ignore the titlebar, since I had not restarted Shell):

screenshot from 2018-04-04 09-09-57

It looks like we're manually setting styling on the widget in the installer instead of leaning on the system stylesheet, and it looks like the actual structure of the widgets might not match what the stylesheet expects.

The Vala source for Granite.StorageBar is available at https://github.com/elementary/granite/blob/master/lib/Widgets/StorageBar.vala. You can also compile Granite locally and run `granite-demo`, then use the GTK inspector to look at the widget structure and classes.

If we need to add borders, that should be done in the Pop! stylesheet, as that's not a generic style that will work across other stylesheets.

### PR DESCRIPTION
**Pull request by isantop**
This PR removes the CSS styling on the Disk Bar widget so that it can be handled by the theme. 

With appropriate changes to system stylesheet: 
screenshot from 2018-04-06 15-45-52

Fixes #29

### CODE REVIEW

**Comment by cassidyjames** [comment]
@isantop there's a tiny margin conflict here. Could you update this PR to not conflict?

**Comment by jackpot51** [comment]
What does the style look like in Adwaita?

**Comment by cassidyjames** [comment]
Adwaita doesn't implement any Granite style classes as far as I'm aware, so it won't likely look perfect (or good at all). But considering the Granite dependency, we just need to make sure it looks correct in stylesheets that support Granite style classes. If we carry any other styles in the installer, we'd want to make sure they're just fallback styles and correctly overridden by the system stylesheet, but I believe that is a larger, separate concern.

**Comment by jackpot51** [comment]
Yes, that is what I want. Fallback styles that are overridden by the system stylesheet.

**Comment by cassidyjames** [comment]
@jackpot51 considering none of the other Granite styles are that way, I think that's outside the scope of this PR.

**Comment by cassidyjames** [comment]
@jackpot51 I'm going ahead with simple fallback styles in this branch if you don't mind

**Comment by jackpot51** [comment]
Thanks @cassidyjames

**Pull request merged**
