### PR TITLE
Update POTFILES

### PR DESCRIPTION
**Pull request by ryonakano**
- Remove files that no longer exist
- Add missing files newly added in the pop fork
- ~~Fix the `warning: unterminated string literal` warning when updating translation files with `ninja -C builddir io.elementary.installer-update-po` command~~

### CODE REVIEW

**Review by jacobgkau — CHANGES_REQUESTED** [review]
This change causes the text to no longer wrap on this page of the installer, and increases the minimum width of the window to accommodate the single line-- see the screenshot below of the installer in a VM, with the window now overflowing the virtual display.

screenshot-2024-08-30-00-13-22

Not sure if a newline can be inserted some other way within the string, or if splitting it into two strings would help get rid of the warning, but the formatting needs to be kept somehow.

**Comment by ryonakano** [comment]
@jacobgkau Thank you for your quick review. I opened #296 to fix the gettext warning without that regression by wrapping the label, would you take a look at it too?

**Comment by ryonakano** [comment]
@jacobgkau Could you take a look at and merge this PR again? This PR is still necessary because updating translation files with `ninja io.elementary.installer-update-po` command fails without this PR.

**Comment by jacobgkau** [comment]
Yes, it's been on my list this week now that https://github.com/pop-os/installer/pull/296 is merged. I'll get to it today. Thanks for following up.

**Review by jacobgkau — APPROVED** [review]
The file additions/removals make sense, and this doesn't seem to impact any behavior of the program.

**Review by mmstick — APPROVED** [review]

**Pull request merged**
