### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by ryonakano**
Installer is now fully translated into Japanese. I also removed the final occurance of the deleted file which I missed in #242.

## Before
VirtualBox_Pop!_OS 20 10 Beta_17_11_2021_08_30_55

## After
VirtualBox_Pop!_OS 20 10 Beta_17_11_2021_08_30_04

### CODE REVIEW

**Review by jacobgkau — APPROVED** [review]
Thank you for the translation! I built locally to test, and this is displaying properly in the installer.

After selecting Japanese, the installer is crashing during installation: [japanese-install-fail.txt](https://github.com/pop-os/installer/files/7558117/japanese-install-fail.txt)
```
[INFO distinst:src/installer/steps/configure/mod.rs:146] chrooting into target on /tmp/distinst.ZG9auOxqwY53
[INFO distinst:crates/chroot/src/command.rs:71] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "check_language_support" "-l" "ja" "--show-installed"
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:244] setting hostname to pop-os
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:253] setting hosts file
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:237] generating machine id via `dbus-uuidgen`
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "sh" "-c" "dbus-uuidgen > /etc/machine-id"
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "ln" "-sf" "/etc/machine-id" "/var/lib/dbus/machine-id"
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:335] creating /etc/resolv.conf
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "ln" "-sf" "../run/systemd/resolve/stub-resolv.conf" "/etc/resolv.conf"
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:230] generating locales via `locale-gen` and `update-locale`
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "locale-gen" "--purge" "ja_JP.UTF-8"
[INFO distinst:crates/chroot/src/command.rs:98] Generating locales (this might take a while)...
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "update-locale" "--reset" "LANG=ja_JP.UTF-8"
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "useradd" "-m" "-G" "adm,sudo,lpadmin" "-s" "/bin/bash" "-c" "system76" "system76"
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "passwd" "system76"
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:105] adding apt-cdrom to /etc/apt/sources.list
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "apt-cdrom" "-o" "Acquire::cdrom::AutoDetect=0" "-o" "Acquire::cdrom::mount=/cdrom" "-o" "APT::CDROM::NoMount=1" "add"
[INFO distinst:crates/chroot/src/command.rs:98] CD-ROM マウントポイント /cdrom/ を使用します
[INFO distinst:crates/chroot/src/command.rs:98] 確認しています... [a355ae6c66bf86720aebb9482924a54d-2]
[INFO distinst:crates/chroot/src/command.rs:98] ディスクのインデックスファイルを走査しています ...
[INFO distinst:crates/chroot/src/command.rs:98] 2 のパッケージインデックス、0 のソースインデックス、0 の翻訳インデックス、1 の署名を見つけました
[INFO distinst:crates/chroot/src/command.rs:98] ラベル 'Pop_OS 21.10 _Impish Indri_ - Release amd64 (20211104)' を見つけました
[INFO distinst:crates/chroot/src/command.rs:98] このディスクは以下のように呼ばれます: 
[INFO distinst:crates/chroot/src/command.rs:98] 'Pop_OS 21.10 _Impish Indri_ - Release amd64 (20211104)'
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:40] installing packages: ["kernelstub", "system76-driver", "system76-driver-nvidia", "e2fsprogs", "dosfstools", "cryptsetup", "cryptsetup-bin", "lvm2", "dmeventd", "dmraid", "kpartx", "kpartx-boot"]
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "apt-get" "install" "-q" "-y" "-o" "Acquire::cdrom::AutoDetect=0" "-o" "Acquire::cdrom::mount=/cdrom" "-o" "APT::CDROM::NoMount=1" "kernelstub" "system76-driver" "system76-driver-nvidia" "e2fsprogs" "dosfstools" "cryptsetup" "cryptsetup-bin" "lvm2" "dmeventd" "dmraid" "kpartx" "kpartx-boot"
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:156] disabling apt-cdrom from /etc/apt/sources.list
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:57] removing packages: ["btrfs-progs", "casper", "cifs-utils", "distinst", "expect", "f2fs-tools", "fatresize", "gettext", "gparted", "gparted-common", "grub-common", "grub2-common", "libdistinst", "libdmraid1.0.0.rc16", "libinih1", "libnss-mymachines", "localechooser-data", "os-prober", "pop-installer", "pop-installer-casper", "pop-shop-casper", "squashfs-tools", "systemd-container", "tcl-expect", "user-setup", "xfsprogs"]
[INFO distinst:crates/chroot/src/command.rs:108] running "chroot" "/tmp/distinst.ZG9auOxqwY53" "apt-get" "purge" "-y" "btrfs-progs" "casper" "cifs-utils" "distinst" "expect" "f2fs-tools" "fatresize" "gettext" "gparted" "gparted-common" "grub-common" "grub2-common" "libdistinst" "libdmraid1.0.0.rc16" "libinih1" "libnss-mymachines" "localechooser-data" "os-prober" "pop-installer" "pop-installer-casper" "pop-shop-casper" "squashfs-tools" "systemd-container" "tcl-expect" "user-setup" "xfsprogs"
[INFO distinst:crates/chroot/src/command.rs:98] パッケージリストを読み込んでいます.
[INFO distinst:crates/chroot/src/command.rs:98]   btrfs-progs* casper* cifs-utils* distinst* dmraid* expect* f2fs-tools*
[INFO distinst:crates/chroot/src/command.rs:98]   fatresize* gettext* gparted* gparted-common* grub-common* grub2-common*
[INFO distinst:crates/chroot/src/command.rs:98]   libdistinst* libdmraid1.0.0.rc16* libinih1* libnss-mymachines*
[INFO distinst:crates/chroot/src/command.rs:98]   localechooser-data* os-prober* pop-installer* pop-installer-casper*
[INFO distinst:crates/chroot/src/command.rs:98]   pop-shop-casper* squashfs-tools* systemd-container* tcl-expect* user-setup*
[INFO distinst:crates/chroot/src/command.rs:98]   xfsprogs*
[INFO distinst:crates/chroot/src/command.rs:98] アップグレード: 0 個、新規インストール: 0 個、削除: 27 個、保留: 0 個。
                                       [INFO distinst:crates/chroot/src/command.rs:98] この操作後に 46.0 MB のディスク容量が解放されます。
                                                          thread '<unnamed>' panicked at 'byte index 58 is not a char boundary; it is inside 'ー' (bytes 56..59)(データベースを読み込んでい`[...]', crates/chroot/src/command.rs:172:31
                                                                       note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                    fatal runtime error: failed to initiate panic, error 5
                                          Aborted (core dumped)
pop-os@pop-os:~$
```
This is also happening on the master branch (not a regression), and looks like it's a similar issue to what https://github.com/pop-os/distinst/pull/267 was intended to fix. Will need to look into that separately.

**Comment by ryonakano** [comment]
Hmm, I don't see that issue with the upstream (elementary's) Installer, there may be some code that can be backported.

**Comment by 13r0ck** [comment]
Hmm that's very weird. The crash is from distinst, but both the pop installer an the elementary installer use the exact same version. :thinking:

**Comment by ryonakano** [comment]
Then the version of distinst used in elementary OS and Pop!_OS might be differ…

**Comment by ryonakano** [comment]
Distinst in elementary OS is `0.3.2~1623858875~20.04~c712fda~dev`:

Screenshot from 2021-11-17 22-53-32

And the one in Pop!_OS is `0.3.2~1635951327~21.10~0f7f8c6`:

VirtualBox_Pop!_OS 20 10 Beta_18_11_2021_07_51_41

**Comment by 13r0ck** [comment]
Oh I was mistaken. Thanks @ryonakano !

**Pull request merged**
