### PR TITLE
WIP: Fix suspension inhibition

### LINKED ISSUE #158: Inhibit suspend
Use systemd-inhibit to prevent suspends during installation

### PR DESCRIPTION
**Pull request by mmstick**
- Suspension inhibition should now work perfectly, w/ no hacks required.
- Removes a Vala singleton, and replaces it with a single Rust function that returns a fd to control the inhibitor lock.
- The restart and shutdown buttons will unlock the inhibitor (by closing it), before attempting to shut down.
- Requires https://github.com/pop-os/distinst/pull/138
- Closes #158

### CODE REVIEW

**Comment by brs17** [comment]
@mmstick should this prohibition on suspending work at any point throughout the installer or only during the actual installation process?

**Comment by mmstick** [comment]
@brs17 It takes place before the UI is rendered.

**Comment by brs17** [comment]
So I started the installer with the above patch on two different machines. I went into the power settings to change the suspend time on battery to a much sooner time, and then left the installer as is. Should the system suspend after the allotted time has passed?

**Comment by jackpot51** [comment]
No, it should not suspend for any reason

**Comment by mmstick** [comment]
@brs17 Not until the inhibitor's file descriptor lock is closed, which is only unlocked on exiting the app / using the restart button in the UI at the end.

**Comment by mmstick** [comment]
Shall we close this?

**Comment by jackpot51** [comment]
Do we have any way forward to prevent suspend, or to make it not cause errors?

**Pull request closed without merging**
