### PR TITLE
Refresh Option

### PR DESCRIPTION
**Pull request by mmstick**
Rebases the previous PR, with the alongside option feature disabled.

Requires https://github.com/pop-os/distinst/pull/168

### CODE REVIEW

**Comment by brs17** [comment]
Issues noticed from https://github.com/pop-os/installer/pull/157:

- [ ] When unlocking an encrypted drive, going back a page relocks the drive, when going forward again and trying to unlock the drive, it initially fails because the name `cryptdata` has already been used. I would think either not relock the device, or recognize that the name has already been used, and use a different name.

- [ ] "Unlock Encrypted" green bar resizes the rest of the page: after decrypting the drive my eye caught the slightly jarring resizing of everything else on that page. (I am not sure this is blocking release)

**Comment by jackpot51** [comment]
@isantop would you take a look at the Unlock Encrypted bar resizing?

**Comment by isantop** [comment]
@jackpot51 Addressed in #174

**Comment by brs17** [comment]
screenshot from 2019-01-24 17-27-09

@isantop The banner seems to come a little too close to the image.

**Comment by mmstick** [comment]
It shouldn't be hugging the top of the window anymore.

**Comment by mmstick** [comment]
This PR has been rebased. Once it's finished, I'll be able to properly rebase the alongside option PR, which builds upon these changes..

**Comment by mmstick** [comment]
Noting that https://github.com/pop-os/distinst/pull/168 contains a lot of fixes for refresh installs.

**Comment by brs17** [comment]
- [ ] 18.04 unencrypted
- [ ] 18.10 unencrypted
- [ ] 18.04 encrypted
- [ ] 18.10 encrypted

**Comment by brs17** [comment]
Looks like when selecting `Refresh Install`(with only one OS installed) the partition is automatically selected. I believe we normally want the user to make the active choice for which partition an (re)install will happen.

**Comment by mmstick** [comment]
The moment of truth :crossed_fingers: 

I remember being told that we should go ahead and invoke the action when there's only one option. Though I also think it's better to have some confirmation before executing a dangerous task like this.

**Comment by brs17** [comment]
That's a fair point, arguably the confirmation **is** that second page. I guess that works for me.

**Comment by brs17** [comment]
Ran into an issue where after a refresh install, I was prompted to unlock the disk even though it was an unencrypted install.

Steps to reproduce:
1. Install unencrypted install of 18.04 to nvme drive
2. Install encrypted install of 18.10 to ssd
3. Refresh install of 18.04
4. Upon reboot and selecting the 18.04 install, prompted to decrypt disk: `Please enter passphrase for disk Samsung... (cryptdata)!`

Maybe this has something to do with me decrypting the 18.10 drive in the installer? Thoughts @mmstick ?

**Comment by mmstick** [comment]
It could very well be that which is causing it. I will replicate it here with some extra logging to verify.

**Comment by mmstick** [comment]
It is adding any encrypted volume to the crypttab that was given to distinst. So we need to ensure that only the volumes which have mount points in the install are added. I'll have a patch for distinst in the `unused-fix` branch soon.

**Pull request merged**
